### ISSUE TITLE
[Refactor] kakao 로그인 ViewModel에서 context을 직접 다루지 않게 수정

### ISSUE THREAD

**Issue by wjdrjs00** [COINKIRI/coinkiri-AOS#5]
## Description 📝

ViewModel에서 context를 직접 다룰 경우 메모리 누수가 발생할 수 있음
-> 이를 해결하기 위해 의존성 주입 방식(Hilt)을 사용하여 context를 주입하는 방법으로 변경

## To-Do ☑️
- [x] repository, repositoryImpl 구현
- [x] UiState 인터페이스 구현
- [x] 기존 viewModel 수정
- [x] RepositoryModule을 통한 의존성 주입
